### ISSUE TITLE
Generating error when implementing

### ISSUE THREAD

**Issue by ruandutrab** [fluttercommunity/responsive_scaffold#33]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
lib\main.dart:1
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_scaffold-1.3.0+2/lib/templates/list/responsive_list.dart:217:11: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
          resizeToAvoidBottomPadding: resizeToAvoidBottomPadding,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_scaffold-1.3.0+2/lib/templates/list/views/tablet.dart:188:15: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
              resizeToAvoidBottomPadding: widget?.resizeToAvoidBottomPadding,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by ruandutrab** [comment]
Allright.

**Comment by Manjit2003** [comment]
@ruandutrab How did you managed to solve this??
